name: flutter_google_places_hoc081098
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 1.0.0-nullsafety.0
homepage: https://github.com/hoc081098/flutter_google_places.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^0.2.0-nullsafety.0
  google_maps_webservice: ^0.0.20-nullsafety.0
  http: ^0.13.0
  rxdart: ^0.26.0-nullsafety.1
  listenable_stream: ^1.0.0-nullsafety.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_google_places_hoc081098/assets/google_black.png
    - packages/flutter_google_places_hoc081098/assets/google_white.png
